version: '2'
services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: commerce
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - 5437:5432/tcp
volumes:
    postgres_data:
        external: true